# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZVWPZMrVQDI24F9aW8N4gU_nWm__etQX
"""

# Máquina de Galton de 3000 canicas
import random
import matplotlib.pyplot as plt

def galton_machine(num_marbles, num_levels):
  """Simula una máquina de Galton y devuelve la distribución de las canicas.

  Args:
    num_marbles: El número de canicas a soltar.
    num_levels: El número de niveles de obstáculos.

  Returns:
    Una lista donde cada elemento representa el número de canicas en cada
    contenedor.
  """

  results = [0] * (num_levels + 1)  # Inicializa la lista de resultados
  for _ in range(num_marbles):
    position = 0
    for _ in range(num_levels):
      if random.random() < 0.5:
        position += 1
    results[position] += 1
  return results


def plot_histogram(results):
  """Grafica el histograma de la distribución de las canicas.

  Args:
    results: Una lista de los resultados, donde cada elemento representa el
             número de canicas en cada contenedor.
  """

  plt.figure(figsize=(10, 6))
  plt.bar(range(len(results)), results)
  plt.xlabel("Contenedores")
  plt.ylabel("Número de canicas")
  plt.title("Distribución de canicas en la máquina de Galton")
  plt.show()

# Ejecuta la simulación y grafica el histograma
results = galton_machine(3000, 12)
plot_histogram(results)